"""added is_nearby colums in anonymous_sessions

Revision ID: 1fdc7b14516d
Revises: 
Create Date: 2026-08-24 15:05:25.928043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fdc7b14516d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    has_column = False
    for col in inspector.get_columns('anonymous_sessions'):
        if col['name'] == 'is_nearby_enabled':
            has_column = True
            break
            
    if not has_column:
        op.add_column(
            'anonymous_sessions',
            sa.Column(
                'is_nearby_enabled',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false')
            )
        )

    op.alter_column(
        'anonymous_sessions',
        'status',
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'active'::character varying")
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anonymous_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_column('anonymous_sessions', 'is_nearby_enabled')
    # ### end Alembic commands ###
